---
title: "COVID-19 Dashboard"
author: "Nguyen Tung Lam"
output:
  flexdashboard::flex_dashboard:
    # "default", "cerulean", "journal", "flatly", "darkly", "readable", "spacelab", "united", "cosmo", "lumen", "paper", "sandstone", "simplex", "yeti"
    theme: united
    source_code: embed
    orientation: rows
    self_contained: FALSE
    logo: ./favicon.ico
    favicon: ./favicon.ico
    social: menu
    # bootstrap_version: 4
runtime: shiny
---

```{r global, include=FALSE, warning=FALSE}
library(flexdashboard)
library(data.table)
library(leaflet)
library(shiny)

# library(bootstraplib)
# bs_theme_new()
# # Color palette derives from https://tombrow.com/dark-mode-website-css
# bs_theme_base_colors(bg = "#444", fg = "#e4e4e4")
# bs_theme_accent_colors(primary = "#e39777", secondary = "#fdce93")
# shinyOptions(plot.autotheme = TRUE)
# bs_theme_preview()

# Ref: https://stackoverflow.com/questions/47064921/leaflet-legend-for-addawesomemarkers-function-with-icons
markerLegendHTML <- function(IconSet) {
  # container div:
  legendHtml <- "<div style='padding: 10px; padding-bottom: 10px;'><h4 style='padding-top:0; padding-bottom:10px; margin: 0;'> Confirmed </h4>"

  n <- 1
  # add each icon for font-awesome icons icons:
  for (Icon in IconSet) {
    if (Icon[["library"]] == "glyphicon") {
      legendHtml <- paste0(
        legendHtml,
        "<div style='width: auto; height: 45px'>",
        "<div style='position: relative; display: inline-block; width: 36px; height: 45px' class='awesome-marker awesome-marker-icon-",
        Icon[["markerColor"]],
        "'>",
        "<i style='margin-left: 4px; margin-top: 11px; color: ",
        Icon[["iconColor"]],
        "' class= 'glyphicon glyphicon-",
        Icon[["icon"]],
        "'></i>",
        "</div>",
        "<p style='position: relative; top: 10px; left: 2px; display: inline-block; ' >",
        names(IconSet)[n],
        "</p>",
        "</div>"
      )
    }
    n <- n + 1
  }
  paste0(legendHtml, "</div>")
}

popup_icons <- awesomeIconList(
  "0" = makeAwesomeIcon(icon = "stats", library = "glyphicon", markerColor = "green"),
  "1-100" = makeAwesomeIcon(icon = "stats", library = "glyphicon", markerColor = "lightblue"),
  "101-10000" = makeAwesomeIcon(icon = "stats", library = "glyphicon", markerColor = "orange"),
  "10001-100000" = makeAwesomeIcon(icon = "stats", library = "glyphicon", markerColor = "red"),
  "100001-1000000" = makeAwesomeIcon(icon = "stats", library = "glyphicon", markerColor = "black"),
  "1000000-" = makeAwesomeIcon(icon = "stats", library = "glyphicon", markerColor = "black", iconColor = "darkred")
)

# data <- readRDS(here::here('covid-19-data.RDS'))
datasource <- "jhu"
if (datasource == "datahub") {
  # https://datahub.io/core/covid-19, it's eventually CSSE data...
  json_file <- "https://datahub.io/core/covid-19/datapackage.json"
  json_data <- jsonlite::fromJSON(paste(readLines(json_file), collapse = ""))

  for (i in 1:length(json_data$resources$datahub$type)) {
    if (json_data$resources$datahub$type[i] == "derived/csv") {
      if (json_data$resources$name[i] == "time-series-19-covid-combined_csv") {
        path_to_file <- json_data$resources$path[i]
        data <- fread(path_to_file)
        break
      }
    }
  }
  data[, Date := as.Date(Date)]
  data[is.na(Recovered), Recovered := 0]
  data <- data[`Province/State` != "Recovered"]
  data[, DeathRate := Deaths / Confirmed]
  setnames(
    data,
    c("Country/Region", "Province/State", "Lat", "Long"),
    c("CountryName", "RegionName", "Latitude", "Longitude")
  )
} else if (datasource == "open-covid-19") {
  data <- fread("https://open-covid-19.github.io/data/data.csv")
  # select regional data
  data <- data[RegionName != "", ]
  data[, DeathRate := Deaths / Confirmed]
} else if (datasource == "jhu") {
  site_link <- paste0(
    "https://raw.githubusercontent.com/",
    "CSSEGISandData/COVID-19/",
    "master/csse_covid_19_data/",
    "csse_covid_19_time_series/"
  )
  confirmed_data <- fread(RCurl::getURL(paste0(site_link, "time_series_covid19_confirmed_global.csv")))
  recovered_data <- fread(RCurl::getURL(paste0(site_link, "time_series_covid19_recovered_global.csv")))
  death_data <- fread(RCurl::getURL(paste0(site_link, "time_series_covid19_deaths_global.csv")))

  # remove columns with NA's
  confirmed_data <- confirmed_data[
    , colSums(!is.na(confirmed_data)) == nrow(confirmed_data),
    with = FALSE
  ]
  recovered_data <- recovered_data[
    , colSums(!is.na(confirmed_data)) == nrow(confirmed_data),
    with = FALSE
  ]
  death_data <- death_data[
    , colSums(!is.na(confirmed_data)) == nrow(confirmed_data),
    with = FALSE
  ]

  cols <- names(recovered_data)[5:dim(recovered_data)[2]]
  recovered_data[, (cols) := lapply(.SD, as.integer), .SDcols = cols]

  confirmed <- melt(
    confirmed_data,
    id = 1:2,
    measure = colnames(confirmed_data)[3:dim(confirmed_data)[2]],
    value.factor = TRUE,
    variable.name = "Date",
    value.name = "Num"
  )
  recovered <- melt(
    recovered_data,
    id = 1:4,
    measure = colnames(recovered_data)[5:dim(recovered_data)[2]],
    value.factor = TRUE,
    variable.name = "Date",
    value.name = "Num"
  )
  death <- melt(
    death_data,
    id = 1:4,
    measure = colnames(death_data)[5:dim(death_data)[2]],
    value.factor = TRUE,
    variable.name = "Date",
    value.name = "Num"
  )

  confirmed = merge(
    confirmed, 
    recovered[, .(`Province/State`, `Country/Region`, Date, Lat, Long)],
    by = c('Province/State', 'Country/Region', 'Date'),
    all.x = TRUE
  )
  confirmed[, Type := "Confirmed"]
  recovered[, Type := "Recovered"]
  death[, Type := "Deaths"]

  data <- rbindlist(list(confirmed, recovered, death), fill = TRUE)
  data <- data[!is.na(data$Lat)]
  data[is.na(Num), Num := 0]
  data[, Date := lubridate::mdy(Date)]

  # data[`Country/Region`=='Taiwan*', `Province/State`:='Taiwan']
  # data[`Country/Region` %in% c('Mainland China', 'Taiwan*'), `Country/Region`:='China']
  # data[`Province/State` %in% c('Hong Kong', 'Macau'), `Country/Region`:='China']

  data <- dcast(data, ... ~ Type, value.var = "Num")
  data <- data[
    !(`Province/State` %in% c("Recovered", "Diamond Princess", "Grand Princess")) &
      !is.na(Confirmed) & !is.na(Deaths) & (Confirmed >= 0) & (Deaths >= 0)
  ]
  data[is.na(Recovered), Recovered := 0]

  # calculate current case: confirmed - death - recovered
  data[, `:=`(
    Current = Confirmed - Deaths - Recovered,
    DeathRate = Deaths / ifelse(Confirmed==0, 1, Confirmed)
  )]
  setnames(
    data,
    c("Country/Region", "Province/State", "Lat", "Long"),
    c("CountryName", "RegionName", "Latitude", "Longitude")
  )
  # colSums(is.na(data))
}

country_data <- data[, .(
  Confirmed = sum(Confirmed),
  Deaths = sum(Deaths)
), .(CountryName, Date)]

country_names <- c("World", unique(country_data[order(-Confirmed)][, CountryName]))

data[, `:=`(
  Date = as.Date(Date),
  icon_group = cut(
    data$Confirmed,
    breaks = c(-1, 0, 100, 10000, 100000, 1000000, 1000000000),
    labels = c("0", "1-100", "101-10000", "10001-100000", "100001-1000000", "1000000-")
  ),
  label = paste0(
    CountryName,
    " <br> ", RegionName,
    " <br> #Confirmed: ", Confirmed,
    " <br> #Deaths: ", Deaths
  )
)]
```

Dashboard {data-icon="ion-stats-bars"}
=====================================

Sidebar {.sidebar data-width=250} 
-----------------------------------------------------------------------

```{r}
library(ggplot2)
library(gganimate)
library(dplyr)
library(tibble)

# Parameters
n_people <- 100
n_infected_start <- 3
max_steps <- 500          # safety stop if infection is slow
infection_radius <- 0.05
infection_chance <- 0.2

# Initialize population
set.seed(123)
people <- tibble(
  id = 1:n_people,
  x = runif(n_people),
  y = runif(n_people),
  infected = c(rep(TRUE, n_infected_start), rep(FALSE, n_people - n_infected_start))
)

frames <- list()
t <- 1

while (any(!people$infected) & t <= max_steps) {
  # Move people randomly
  people <- people %>%
    mutate(
      x = pmin(pmax(x + runif(n(), -0.02, 0.02), 0), 1),
      y = pmin(pmax(y + runif(n(), -0.02, 0.02), 0), 1)
    )
  
  # Infection spread
  new_infected <- people
  for (i in which(people$infected)) {
    distances <- sqrt((people$x - people$x[i])^2 + (people$y - people$y[i])^2)
    newly <- which(distances < infection_radius & !people$infected)
    for (j in newly) {
      if (runif(1) < infection_chance) {
        new_infected$infected[j] <- TRUE
      }
    }
  }
  people <- new_infected
  people$time <- t
  frames[[t]] <- people
  t <- t + 1
}

simulation_data <- bind_rows(frames)

# Plot with white background and dots only
p <- ggplot(simulation_data, aes(x, y, color = infected, group = id)) +
  geom_point(size = 3) +
  scale_color_manual(values = c("FALSE" = "blue", "TRUE" = "red")) +
  theme_void() +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "white", color = NA)
  ) +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1), expand = FALSE) +
  transition_time(time) +
  ease_aes('linear')

# Render animation with actual frames run
animate(p, nframes = length(frames), fps = 10, width = 600, height = 600, renderer = gifski_renderer("www/covid_simulation.gif"))

```

```{r}
# Parameters
n_people <- 150
n_infected_start <- 75  # half infected on one side
max_steps <- 200
infection_radius <- 0.05
infection_chance <- 0.2
quarantine_duration <- 30

# Gate
gate_position <- 0.5
gate_width_max <- 0.3
gate_open_start <- 40
gate_open_end <- 100

get_gate_opening <- function(t) {
  if (t < gate_open_start) return(0)
  if (t >= gate_open_end) return(gate_width_max)
  return((t - gate_open_start) / (gate_open_end - gate_open_start) * gate_width_max)
}

# Initial placement
set.seed(123)
people <- tibble(
  id = 1:n_people,
  x = c(runif(n_infected_start, 0, 0.45), runif(n_people - n_infected_start, 0.55, 1)),
  y = runif(n_people),
  infected = c(rep(TRUE, n_infected_start), rep(FALSE, n_people - n_infected_start))
)

frames <- list()
t <- 1

while (any(!people$infected) & t <= max_steps) {
  
  gate_opening <- get_gate_opening(t)
  gate_lower <- 0.5 - gate_opening / 2
  gate_upper <- 0.5 + gate_opening / 2
  
  # Movement logic with gate and quarantine
  people <- people %>%
    rowwise() %>%
    mutate(
      x_new = x + ifelse(infected & t <= quarantine_duration, 0, runif(1, -0.02, 0.02)),
      y_new = y + ifelse(infected & t <= quarantine_duration, 0, runif(1, -0.02, 0.02)),
      x_new = pmin(pmax(x_new, 0), 1),
      y_new = pmin(pmax(y_new, 0), 1),
      x = ifelse(
        ((x < gate_position & x_new >= gate_position) | (x > gate_position & x_new <= gate_position)) &
        !(y > gate_lower & y < gate_upper),
        x, x_new
      ),
      y = y_new
    ) %>% ungroup()
  
  # Infection logic
  new_infected <- people
  for (i in which(people$infected)) {
    distances <- sqrt((people$x - people$x[i])^2 + (people$y - people$y[i])^2)
    candidates <- which(distances < infection_radius & !people$infected)
    for (j in candidates) {
      if (runif(1) < infection_chance) {
        new_infected$infected[j] <- TRUE
      }
    }
  }
  
  people <- new_infected
  people$time <- t
  people$gate_lower <- gate_lower
  people$gate_upper <- gate_upper
  frames[[t]] <- people
  t <- t + 1
}

simulation_data <- bind_rows(frames)

# Gate line segments
gate_lines <- simulation_data %>%
  distinct(time, gate_lower, gate_upper) %>%
  mutate(x = gate_position, xend = gate_position,
         y1 = 0, yend1 = gate_lower,
         y2 = gate_upper, yend2 = 1)

# Plot
p <- ggplot(simulation_data, aes(x, y, color = infected, group = id)) +
  geom_point(size = 2.5) +
  geom_segment(data = gate_lines,
               aes(x = x, xend = xend, y = y1, yend = yend1),
               inherit.aes = FALSE, color = "black", size = 4) +
  geom_segment(data = gate_lines,
               aes(x = x, xend = xend, y = y2, yend = yend2),
               inherit.aes = FALSE, color = "black", size = 4) +
  scale_color_manual(values = c("FALSE" = "#999999", "TRUE" = "#CC3300")) +
  theme_void() +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "white", color = NA)
  ) +
  coord_fixed(xlim = c(0, 1), ylim = c(0, 1)) +
  transition_time(time) +
  ease_aes('linear')

# Export
animate(p, nframes = length(frames), fps = 10, width = 600, height = 500,
        renderer = gifski_renderer("www/covid_gate.gif"))
```
